export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_BENEFICIARIO = "SET_BENEFICIARIO";
export const SET_DATOS_COMPRA = "SET_DATOS_COMPRA";
export const BENEFICIARIO_LOADING = "BENEFICIARIO_LOADING";
export const BORRAR_BENEFICIARIO_ACTUAL = "BORRAR_BENEFICIARIO_ACTUAL";
export const BORRAR_COMPRA_ACTUAL = "BORRAR_COMPRA_ACTUAL";
export const BENEFICIARIO_NO_ENCONTRADO = "BENEFICIARIO_NO_ENCONTRADO";
export const SET_CONTRATO = "SET_CONTRATO";
export const SET_VALOR_VALE = "SET_VALOR_VALE";
export const SET_TIPOS_IDENTIFICACION = "SET_TIPOS_IDENTIFICACION";
export const TIPOS_IDENTIFICACION_LOADING = "TIPOS_IDENTIFICACION_LOADING";
export const SET_TIPO_IDENTIFICACION_BENEFICIARIO =
  "SET_TIPO_IDENTIFICACION_BENEFICIARIO";
export const CONTRATO_LOADING = "CONTRATO_LOADING";
export const TIRA_AUDITORA_LOADING = "TIRA_AUDITORA_LOADING";
